brew "coreutils"
brew "git"
brew "python"
brew "mas"
cask_args appdir: "/Applications"
tap "homebrew/cask"
cask "iterm2"
cask "atom"
cask "sublime-text"
cask "google-chrome"
mas "Garageband", id: 682658836
mas "Magnet", id: 441258766
